python3 ASTARBusQueue.py ./ASTAR-tests/st1.prob 1
python3 ASTARBusQueue.py ./ASTAR-tests/st1.prob 2
python3 ASTARBusQueue.py ./ASTAR-tests/st1.prob 3
python3 ASTARBusQueue.py ./ASTAR-tests/st2.prob 1
python3 ASTARBusQueue.py ./ASTAR-tests/st2.prob 2
python3 ASTARBusQueue.py ./ASTAR-tests/st2.prob 3
python3 ASTARBusQueue.py ./ASTAR-tests/st3.prob 1
python3 ASTARBusQueue.py ./ASTAR-tests/st3.prob 2
python3 ASTARBusQueue.py ./ASTAR-tests/st3.prob 3
python3 ASTARBusQueue.py ./ASTAR-tests/st4.prob 1
python3 ASTARBusQueue.py ./ASTAR-tests/st4.prob 2
python3 ASTARBusQueue.py ./ASTAR-tests/st4.prob 3
python3 ASTARBusQueue.py ./ASTAR-tests/st5.prob 1
python3 ASTARBusQueue.py ./ASTAR-tests/st5.prob 2
python3 ASTARBusQueue.py ./ASTAR-tests/st5.prob 3